import json
import re
from pydantic import BaseModel


class PRAnalysis(BaseModel):
    modification_tag: str
    summary: str
    risk_notes: list[str]
    test_checklist: list[str]


def parse_response(content: str) -> PRAnalysis:
    # Strip markdown fences if present
    content = content.strip()
    content = re.sub(r'^```(?:json)?\s*', '', content)
    content = re.sub(r'\s*```$', '', content)

    data = json.loads(content)
    return PRAnalysis(**data)


def format_comment(analysis: PRAnalysis) -> str:
    lines = [
        "## PR Analysis",
        "",
        f"**Tag:** `{analysis.modification_tag}`",
        "",
        "### Summary",
        analysis.summary,
        "",
    ]

    if analysis.risk_notes:
        lines += ["### Risk Notes", ""]
        for note in analysis.risk_notes:
            lines.append(f"- {note}")
        lines.append("")

    if analysis.test_checklist:
        lines += ["### Test Checklist", ""]
        for item in analysis.test_checklist:
            lines.append(f"- [ ] {item}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [PR Summary & Risk Generator](https://github.com/GuruVithiya/PR-SUMMARY)*")

    return "\n".join(lines)
